spring:
  datasource:
    url: jdbc:mysql://zanditime.cjntcovet9jv.ap-northeast-2.rds.amazonaws.com:3306/zandiTimeTest
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: master
    password: zandi1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
#          google:
#            client-id: 795344605481-eh9clt5aracqv6avsfmr3ca611nemc7k.apps.googleusercontent.com
#            client-secret: 9LAFQ24GSN
#            scope:
#              - email
#              - profile
          google:
            client-id: 154711632031-e6a1lsonnrt68haimdnlou81n254rdug.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

#server:
#  servlet:
#    session:
#      timeout: 43200m      # 60m * 24h * 30d5
#      cookie:
#        max-age: 43200m    # 60m * 24h * 30d
#        name: SID
#        http-only: true
#        secure: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace


